name: Compilation

on: push

env:
  EXECUTABLES: "42sh"

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
      - id: check_program_compilation
        run: make
      - name: Clean up
        run: make clean
      - name: Verify executables
        run: |
          OIFS=$IFS
          IFS=','
          for x in $EXECUTABLES; do
            if [ ! -x "$x" ]; then
              echo "Error: $x does not exist or is not executable" >&2
              exit 1
            fi
          done
          IFS=$OIFS
